# Generated by Django 4.2.23 on 2025-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
